services:
  app:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: vue-project
    ports:
      - '5173:5173'
    volumes:
      - ./front:/app
      - /app/node_modules
    stdin_open: true
    tty: true

    command: npm run dev -- --host 0.0.0.0
