name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
        working-directory: front
      - run: npm run build
        working-directory: front
      - run: npm run test:unit
        working-directory: front
